### ISSUE TITLE
0.4.0 Roadmap

### ISSUE THREAD

**Issue by m-clark** [m-clark/mixedup#34]
Package needs some love.  

- [x] General update for R 4.2 and related package updates
  - [x] Update test objects with results from current packages
  - [x] Update tests given current test objects
  - [x] Improve code throughout
    - [x] Change stops to {assertthat}
    - [x] Use `{{}}` where applicable
- [x] #8 
- [x] #31 
- [x] #10 
  - As long as this only warns but still allows install I think it's okay to close
- [x] Misc issues
  - [x] #27 
  - [x] #29  
  - [x] #32
